version: '3.8'

services:

  rethinkdb:
    image: rethinkdb:2.4
    ports:
      - "8080:8080"
      - "28015:28015"
    volumes:
      - rethinkdb_data:/apps/rethinkdb/data

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  rabbitmq_meeting_books:
    container_name: rabbitmq_meeting_books
    volumes:
      - rabbitmq_data2:/var/lib/rabbitmq
    build:
      context: .
      dockerfile: Dockerfile
      target: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 10s
      start_period: 1s
      retries: 5
#  worker:
#    container_name: worker
#    restart: always
#    build:
#      context: .
#      dockerfile: Dockerfile
#    working_dir: /application
#    command: celery -A tasks worker --loglevel=INFO
#    volumes:
#      - .:/application/app
#    ports:
#      - 5000:5000
#    depends_on:
#      rabbitmq_meeting_books:
#        condition: service_healthy
#      rethinkdb:
#        condition: service_started
#      redis:
#        condition: service_started

#  api:
#    container_name: api
#    build:
#      context: .
#      dockerfile: Dockerfile
#    working_dir: /application
#    command: python3 app.py
#    ports:
#      - 3000:3000
#    depends_on:
#      worker:
#        condition: service_started


volumes:
  rethinkdb_data: null
  redis: null
  rabbitmq_data2: null